### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by MrBurnsAI** [amjadraza/embedchain-streamlit-app#1]
Hi,

I do get the following error:

  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/embedchain/embedchain.py", line 184, in retrieve_from_database
    content = result_formatted[0][0].page_content
IndexError: list index out of range

Any idea?

thanks,
mario

**Comment by amjadraza** [comment]
Are you running locally? I am having same issue with my streamlit app too

**Comment by amjadraza** [comment]
https://github.com/embedchain/embedchain/issues/98

I have created the issue with embedchain. Let us wait their response.

**Comment by MrBurnsAI** [comment]
It works if I run with streamlit command but always generates the same response - no matter which youtube url I post

**Comment by amjadraza** [comment]
Hi @MrBurnsAI, I am experiencing a problem with the embedchain package and have already reported it to the concerned team. It was working perfectly fine a few days ago, but after I deleted and recreated the database, the issue persisted.

**Comment by amjadraza** [comment]
Updated the app with some changes. This issue must be solved now.
